# This is a boilerplate parameters config generated for pipeline 'symptom_checker'
# using Kedro 0.17.5.
#
# Documentation for this file format can be found in "Parameters"
# Link: https://kedro.readthedocs.io/en/0.17.5/04_kedro_project_setup/02_configuration.html#parameters

common_conf:
  symp_rec_threshold: 0.5
  num_workers: 10
  seed: 7
  n_last_train_batchs_for_metrics: 10
  max_iterations: 50
  model_class_path: src/repo_for_article_about_symptom_checker_based_on_deep_learning_network_with_logic_regularization/pipelines/symptom_checker/models.py
  explicit_data: symptoms
  hidden_size: 5000
  activ_f: ReLU


SymptomChecker_mz_conf:
  num_hidden_layers: 2
  1_hidden_size: 6000
  2_hidden_size: 3000
  entropy_threshold: 0.5
  symp_rec_loss_coef: 1.6
  drop_prob: 0.4
  lr: 5.e-5
  epochs: 35

SymptomChecker_dxy_conf:
  num_hidden_layers: 1
  1_hidden_size: 10000
  entropy_threshold: 0.30100000000000005
  symp_rec_loss_coef: 0.6000000000000001
  drop_prob: 0.5
  lr: 0.001
  epochs: 5

SymptomChecker_symcat_200_conf:
  num_hidden_layers: 1
  1_hidden_size: 8000
  entropy_threshold: 0.3
  symp_rec_loss_coef: 1.0
  drop_prob: 0.5
  lr: 1.e-3
  epochs: 5

SymptomChecker_symcat_300_conf:
  num_hidden_layers: 1
  1_hidden_size: 8000
  entropy_threshold: 0.4
  symp_rec_loss_coef: 1.0
  drop_prob: 0.5
  lr: 1.e-2
  epochs: 10

SymptomChecker_symcat_400_conf:
  num_hidden_layers: 1
  1_hidden_size: 8000
  entropy_threshold: 0.4
  symp_rec_loss_coef: 1.0
  drop_prob: 0.5
  lr: 1.e-2
  epochs: 10